#!/usr/bin/env python3

# Random sentence generator
# CMPU 240, Fall 2019

import sys
import fileinput
import random
import re

grammar = {}


def error(msg):
    """Print an error message and exit."""
    print(msg, file=sys.stderr)
    sys.exit()


for line in fileinput.input():
    # Skip blank lines
    if not line.strip():
        continue

    # Split the line into the head and a list of bodies
    try:
        head, bodies = line.strip().split(" -> ")
        bodies = bodies.split(" | ")
    except ValueError:
        error("Bad input line: " + line.strip())

    if head in grammar:
        error("All rules for a head need to be on the same line.")

    grammar[head] = bodies

string = "<start>"

def generateSentence(fileinput):
# select one production of this symbol randomly
        rand_prod = random.choice(self.prod[fileinput])

        for sym in rand_prod:
            # for non-terminals, recurse
            if sym in self.prod:
                string.append(sym)
            else:
                string += sym 

        return string
# Expand string, printing each step of the expansion, until there are
# no non-terminals left.
